[phases.setup]
nixPkgs = ["bun", "openssl", "openssl_3"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run db:generate", "bun run next build"]

[start]
cmd = "next start -p ${PORT:-3000}"
